name: 'AWS initial basic environment on AWS Portal'
on:
  push:
    tags:
      - 'aws-init-env*'
  pull_request:
    tags:
      - 'aws-init-env*'

jobs:
  create-environment:
    runs-on: ubuntu-latest
    env:
      working-directory: ./aws/
    
    defaults:
      run:
        working-directory: ${{env.working-directory}}

    steps:
      # Checkout code
    - uses: actions/checkout@master
      name: Git checkout code

      # Configure AWS credential with region
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: ${{ secrets.AWS_REGION }}

      # Create S3 bucket for housing state file
    - name: Create S3 bucket for housing state file
      run: |
        if aws s3 ls "s3://${{ secrets.AWS_BUCKETNAME }}" 2>&1 | grep -q 'The specified bucket does not exist'
        then
        aws s3api create-bucket --bucket ${{ secrets.AWS_BUCKETNAME }} --acl private --region ${{ secrets.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
        #aws s3api put-bucket-versioning --bucket ${{ secrets.AWS_BUCKETNAME }} --versioning-configuration Status=Enabled
        fi

      # Sync result back to repository
    - uses: actions-js/push@master
      name: Commit and push result back
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "Commit for update result create environment"