name: 'AWS Initial Foundation'
on:
  push:
    tags:
      - 'aws-init-foundation*'
  pull_request:
    tags:
      - 'aws-init-foundation*'

jobs:
  create-foundation1:
    runs-on: ubuntu-latest
    env:
      working-directory: ./aws/
      TF_VAR_access_key: ${{ secrets.AWS_ACCESSKEY }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET }}
      TF_VAR_region: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: ${{env.working-directory}}

    steps:
      # Checkout code
    - uses: actions/checkout@master
      name: Git checkout code

      # Prepare Configuration and Seed file 
    - name: Setup system configruation
      run: |
        # Clone template file and preparation
        cp ./99.Systemplate/00_provider.tftemplate ./99.Systemplate/00_provider.tf
        sed -i -e "s/<bucket>/${{ secrets.AWS_BUCKETNAME }}/g" ./99.Systemplate/00_provider.tf
        sed -i -e "s/<region>/${{ secrets.AWS_REGION }}/g" ./99.Systemplate/00_provider.tf

        # Copy all properties file to target folder
        cp ./99.Systemplate/00_provider.tf ./1.Environment/01_BaseEnvironment/00_provider.tf
        cp ./99.Systemplate/00_provider.tf ./1.Environment/02_InitialParameter/00_provider.tf
        cp ./99.Systemplate/global_variable.auto.tfvars ./1.Environment/01_BaseEnvironment/global_variable.auto.tfvars
        cp ./99.Systemplate/global_variables.tf ./1.Environment/01_BaseEnvironment/global_variables.tf
        cp ./99.Systemplate/global_variable.auto.tfvars ./1.Environment/02_InitialParameter/global_variable.auto.tfvars
        cp ./99.Systemplate/global_variables.tf ./1.Environment/02_InitialParameter/global_variables.tf

        # Verify file properties
        pwd
        ls ./1.Environment/01_BaseEnvironment/
        ls ./1.Environment/02_InitialParameter/


  create-foundation2:
    needs: [create-foundation1]
    runs-on: ubuntu-latest
    env:
      working-directory: ./aws/1.Environment/01_BaseEnvironment/
      TF_VAR_access_key: ${{ secrets.AWS_ACCESSKEY }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET }}
      TF_VAR_region: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: ${{env.working-directory}}

    steps:
    - name: Test Debug
      run: |
        # Test
        cd ./aws/1.Environment/01_BaseEnvironment/
        pwd
        ls -lh

    - name: Load Terraform to operate
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.9

    - name: Terraform readiness verify
      id: fmt1
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Terraform initialize
      id: init1
      run: terraform init -input=false

    - name: Terraform validation configuration step1
      id: validate1
      run: terraform validate -no-color

    - name: Terraform configuration step2
      id: plan1
      run: terraform plan -no-color -out=tfplan -input=false
      continue-on-error: true

    - name: Terraform create
      id: apply1
      run: terraform apply -input=false tfplan
      continue-on-error: true

    - name: Terraform export output
      id: output1
      run: terraform output > ../../99.Systemplate/system_variable.auto.tfvars
      continue-on-error: true

      # CleanUp process
    - name: CleanUp temporary file
      run: | 
        rm ./global_variable.auto.tfvars
        rm ./global_variables.tf


  create-foundation3:
    needs: [create-foundation2]
    runs-on: ubuntu-latest
    env:
      working-directory: ./aws/02_InitialParameter/
      TF_VAR_access_key: ${{ secrets.AWS_ACCESSKEY }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET }}
      TF_VAR_region: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: ${{env.working-directory}}

    steps:
    - name: Terraform readiness verify
      id: fmt2
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Terraform initialize
      id: init2
      run: terraform init -input=false

    - name: Terraform validation configuration step1
      id: validate2
      run: terraform validate -no-color

    - name: Terraform configuration step2
      id: plan2
      run: terraform plan -no-color -out=tfplan -input=false
      continue-on-error: true

    - name: Terraform create
      id: apply2
      run: terraform apply -input=false tfplan
      continue-on-error: true

      # CleanUp process
    - name: CleanUp temporary file
      run: | 
        rm ./global_variable.auto.tfvars
        rm ./global_variables.tf
        rm ./system_variable.auto.tfvars
        rm ./system_variables.tf


  create-foundation4:
    needs: [create-foundation3]
    runs-on: ubuntu-latest
    env:
      working-directory: ./aws/
      TF_VAR_access_key: ${{ secrets.AWS_ACCESSKEY }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET }}
      TF_VAR_region: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
    - uses: actions-js/push@master
      name: Commit and push result back
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "Commit for update result create environment"